#! /bin/sh
# Various postinst jobs for lite-themes

gtk-update-icon-cache -t /usr/share/icons/Faenza-Dark /usr/share/icons/Faenza /usr/share/icons/hicolor /usr/share/icons/gnome

set -e

# Generate font cache
cd /usr/share/fonts/truetype/

sudo chown root:root Droid*
sudo chmod 755 Droid*

sudo fc-cache -f -v

